### ISSUE TITLE
[linter] arrow-spacing null node

### ISSUE THREAD

**Issue by haltcase** [lightscript/lightscript#35]
### repro

```js
x = b -> c
```

### stack

```console
Cannot read property 'range' of null
TypeError: Cannot read property 'range' of null
    at TokenStore.getTokenBefore (/home/ubuntu/workspace/node_modules/eslint/lib/token-store/index.js:318:17)
    at getTokens (/home/ubuntu/workspace/node_modules/eslint/lib/rules/arrow-spacing.js:63:36)
    at EventEmitter.spaces (/home/ubuntu/workspace/node_modules/eslint/lib/rules/arrow-spacing.js:89:28)
    at emitOne (events.js:120:20)
    at EventEmitter.emit (events.js:210:7)
    at NodeEventGenerator.applySelector (/home/ubuntu/workspace/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/home/ubuntu/workspace/node_modules/eslint/lib/util/node-event-generator.js:294:22)
    at NodeEventGenerator.enterNode (/home/ubuntu/workspace/node_modules/eslint/lib/util/node-event-generator.js:308:14)
    at CodePathAnalyzer.enterNode (/home/ubuntu/workspace/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:602:23)
    at CommentEventGenerator.enterNode (/home/ubuntu/workspace/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
```

Discovered while working on the cli:
https://github.com/citycide/lightscript-cli/blob/ac44f424d1d455bbe7dd335557d51a822abc47dd/src/commands/compile.lsc#L48

**Comment by rattrayalex** [comment]
My hunch is that `isArrowToken` in `eslint/lib/ast-types.js` needs to be expanded to include lsc arrows
