### ISSUE TITLE
[plugin] document build setup steps

### ISSUE THREAD

**Issue by plexigras** [lightscript/lightscript#43]
what i did:

```
$ git clone https://github.com/lightscript/babel-plugin-lightscript
$ cd babel-plugin-lightscript
$ yarn install
$ yarn test
```

error message for every test:
```
      at node_modules/babel-helper-transform-fixture-test-runner/node_modules/babel-core/lib/transformation/file/options/option-manager.js:176:17
      at Array.map (<anonymous>)
      at Function.normalisePlugins (node_modules/babel-helper-transform-fixture-test-runner/node_modules/babel-core/lib/transformation/file/options/option-manager.js:154:20)
      at OptionManager.mergeOptions (node_modules/babel-helper-transform-fixture-test-runner/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:36)
      at OptionManager.init (node_modules/babel-helper-transform-fixture-test-runner/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
      at File.initOptions (node_modules/babel-helper-transform-fixture-test-runner/node_modules/babel-core/lib/transformation/file/index.js:216:65)
      at new File (node_modules/babel-helper-transform-fixture-test-runner/node_modules/babel-core/lib/transformation/file/index.js:139:24)
      at Pipeline.transform (node_modules/babel-helper-transform-fixture-test-runner/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
      at run (node_modules/babel-helper-transform-fixture-test-runner/lib/index.js:241:20)
      at runTask (node_modules/babel-helper-transform-fixture-test-runner/lib/index.js:63:13)
      at tryBlock (assert.js:582:5)
      at innerThrows (assert.js:601:18)
      at Function.throws (assert.js:625:3)
      at Context.<anonymous> (node_modules/babel-helper-transform-fixture-test-runner/lib/index.js:83:30)
```

**Comment by rattrayalex** [comment]
Yeah, sorry. You have to do some deep `npm link`ing IIRC. I may have the steps written down. 
cc @wcjohnson

**Comment by rattrayalex** [comment]
Ah, @plexigras , there are steps outlined in the readme. Did you try those?

**Comment by plexigras** [comment]
i don't see anything in the readme but i got it to work just now using this repo and `npm run setup` and `self-link`

**Comment by rattrayalex** [comment]
Great; closing for now, but if you run into other build problems, feel free to reopen here.
